import Head from "next/head";
// import Link from "next/link";
import Script from "next/script";
import { useState, useEffect } from "react";

export default function Home() {
  const [lt, setLT] = useState("test label");
  const [val, setValue] = useState("test val");
  const [header, setHeader] = useState("Header");
  // const [ran, setRan] = useState(false);

  // useEffect(() => {
  //   if (
  //     !ran &&
  //     typeof window !== "undefined" &&
  //     typeof window.JFCustomWidget !== "undefined"
  //   ) {
  //     console.log("window ready");
  //     console.log("ran", ran);
  //     console.log(window.JFCustomWidget);
  //   }
  // }, [ran, val]);
  const onLoad = () => {
    while (
      typeof window == "undefined" ||
      typeof window.JFCustomWidget == "undefined"
    ) {
      console.log("waiting for defined");
    }
    const JF = window.JFCustomWidget;
    console.log("loaded");
    console.log(window);
    console.log(JF);
    const label = JF.getWidgetSetting("QuestionLabel");
    console.log("label", label);
    JF.subscribe("ready", function () {
      // setRan(true);

      console.log("JF ready");
      const label = JF.getWidgetSetting("QuestionLabel");
      console.log("label", label);

      setLT(label);
      //subscribe to form submit event
      JF.subscribe("submit", function () {
        console.log("JF submit subscribe function");
        const msg = {
          //you should valid attribute to data for JotForm
          //to be able to use youw widget as required
          valid: true,
          value: val,
        };

        // send value to JotForm
        JF.sendSubmit(msg);
      });
    });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <script
        type="text/javascript"
        src="https://js.jotform.com/JotFormCustomWidget.min.js"
        async
        onLoad={onLoad}
      ></script>
      <main>
        <div id="main">
          <h3>{header}</h3>
          <span>{lt} </span>
          <input
            type="text"
            value={val}
            onChange={(e) => {
              setValue(e.target.value);
              setLT(e.target.value);
              setHeader(e.target.value);
            }}
          />
        </div>
      </main>
    </>
  );
}
