import Head from "next/head";
import Link from "next/link";
import Script from "next/script";

import { api } from "~/utils/api";

const func = () => {
  //always subscribe to ready event and implement widget related code
  //inside callback function , it is the best practice while developing widgets
  // JFCustomWidget.subscribe("ready", function () {
  //   const label = JFCustomWidget.getWidgetSetting("QuestionLabel");
  //   document.getElementById("labelText").innerHTML = label;
  //   //subscribe to form submit event
  //   JFCustomWidget.subscribe("submit", function () {
  //     const msg = {
  //       //you should valid attribute to data for JotForm
  //       //to be able to use youw widget as required
  //       valid: true,
  //       value: document.getElementById("userInput").value,
  //     };
  //     // send value to JotForm
  //     JFCustomWidget.sendSubmit(msg);
  //   });
  // });
  JFCustomWidget.subscribe("ready", function () {
    const label = JFCustomWidget.getWidgetSetting("QuestionLabel");
    console.log(label);
    // document.getElementById("labelText").innerHTML = label;
    //subscribe to form submit event
    JFCustomWidget.subscribe("submit", function () {
      const msg = {
        //you should valid attribute to data for JotForm
        //to be able to use youw widget as required
        valid: true,
        value: "user input", //document.getElementById("userInput").value,
      };
      // send value to JotForm
      JFCustomWidget.sendSubmit(msg);
    });
  });
};

export default function Home() {
  const hello = api.post.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Script
        src="https://js.jotform.com/JotFormCustomWidget.min.js"
        strategy="lazyOnload"
        onLoad={() => {
          console.log(`script loaded correctly, window.FB has been populated`);
          func();
        }}
      />
      <main>this is a test</main>
    </>
  );
}
