import Head from "next/head";
// import Link from "next/link";
import Script from "next/script";
import { useState } from "react";

export default function Home() {
  const [lt, setLT] = useState("test label");
  const [val, setValue] = useState("test val");
  //always subscribe to ready event and implement widget related code
  //inside callback function , it is the best practice while developing widgets

  window.JFCustomWidget.subscribe("ready", function () {
    console.log("JF ready");
    const label = window.JFCustomWidget.getWidgetSetting("QuestionLabel");

    setLT(label);
    //subscribe to form submit event
    window.JFCustomWidget.subscribe("submit", function () {
      console.log("JF submit subscribe function");
      const msg = {
        //you should valid attribute to data for JotForm
        //to be able to use youw widget as required
        valid: true,
        value: val,
      };

      // send value to JotForm
      window.JFCustomWidget.sendSubmit(msg);
    });
  });
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div id="main">
          <h3>This is my first widget.</h3>
          <span>{lt} </span>
          <input
            type="text"
            value={val}
            onChange={(e) => {
              setValue(e.target.value);
              setLT(e.target.value);
            }}
          />
        </div>
      </main>
    </>
  );
}
